name = "basic"
compatibility_date = "2024-07-01"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]

#[vars]
#MY_VAR = "my-variable"

#[[kv_namespaces]]
#binding = "MY_KV_NAMESPACE"
#id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

#[[d1_databases]]
#binding = "MY_DB"
#database_name = "my-database"
#database_id = ""